export interface User {
  id?: string;
  uid: string;
  email: string;
  phone?: string;
  name: string;
  shopId?: string;
  roleId?: string;
  planId?: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  lastLogin?: Date;
  lastLoginAt?: Date;
  displayName?: string;
  mobile?: string;
  emailVerified?: boolean;
  mobileVerified?: boolean;
  isBlocked?: boolean;
  kycStatus?: "pending" | "verified" | "rejected";
  gstNumber?: string;
  panNumber?: string;
  additionalPermissions?: string[];
  restrictedPermissions?: string[];
  failedLoginAttempts?: number;
  lastFailedLoginAt?: Date | string | null;
  lockUntil?: Date | string | null;
  accountStatus?: "active" | "suspended" | "disabled" | "archived" | "deleted";
  suspensionReason?: string | null;
  suspendedAt?: Date | string | null;
  suspendedBy?: string | null;
  metadata?: Record<string, any>;
}
