import { AnalyticsDefinition, AnalyticsPageKey } from './analytics.types';

export const ANALYTICS_NAV_ITEMS: Array<{
  key: AnalyticsPageKey;
  label: string;
  route: string;
  permission: string;
  feature: string;
}> = [
  {
    key: 'sales',
    label: 'Sales Analytics',
    route: 'sales',
    permission: 'view_sales_analytics',
    feature: 'analytics_sales',
  },
  {
    key: 'customers',
    label: 'Customer Analytics',
    route: 'customers',
    permission: 'view_customer_analytics',
    feature: 'analytics_customers',
  },
  {
    key: 'products',
    label: 'Product Performance',
    route: 'products',
    permission: 'view_product_performance',
    feature: 'analytics_products',
  },
  {
    key: 'branches',
    label: 'Branch Performance',
    route: 'branches',
    permission: 'view_branch_performance',
    feature: 'analytics_branches',
  },
];

export const ANALYTICS_DEFINITIONS: Record<AnalyticsPageKey, AnalyticsDefinition> = {
  sales: {
    key: 'sales',
    title: 'Sales Analytics',
    subtitle: 'Revenue rhythm, order flow, and conversion momentum for the selected shop.',
    description: 'Track billing performance with summary metrics, time-series charts, and top-performing segments.',
    permission: 'view_sales_analytics',
    feature: 'analytics_sales',
    chartType: 'line',
    chartTitle: 'Sales Trend',
    chartSubtitle: 'Live revenue and order movement for the selected time window.',
    labels: [],
    series: [],
    summaryCards: [],
    branchOptions: [{ label: 'All Branches', value: 'all' }],
    insights: [],
    columns: [],
    rows: [],
    emptyTitle: 'No sales activity found',
    emptyDescription: 'Try another date range or branch filter to view sales insights.',
  },
  customers: {
    key: 'customers',
    title: 'Customer Analytics',
    subtitle: 'Returning customer behavior, retention strength, and channel engagement.',
    description: 'Understand how shoppers return, spend, and engage across the selected time window.',
    permission: 'view_customer_analytics',
    feature: 'analytics_customers',
    chartType: 'bar',
    chartTitle: 'Customer Acquisition Mix',
    chartSubtitle: 'Live acquisition and retention distribution.',
    labels: [],
    series: [],
    summaryCards: [],
    branchOptions: [{ label: 'All Branches', value: 'all' }],
    insights: [],
    columns: [],
    rows: [],
    emptyTitle: 'No customer insights available',
    emptyDescription: 'Customer analytics will appear once the selected branch has activity.',
  },
  products: {
    key: 'products',
    title: 'Product Performance',
    subtitle: 'Top movers, margin-friendly styles, and category momentum across the shop.',
    description: 'Monitor product demand with SKU-level ranking and category performance snapshots.',
    permission: 'view_product_performance',
    feature: 'analytics_products',
    chartType: 'bar',
    chartTitle: 'Category Performance',
    chartSubtitle: 'Live product demand by category.',
    labels: [],
    series: [],
    summaryCards: [],
    branchOptions: [{ label: 'All Branches', value: 'all' }],
    insights: [],
    columns: [],
    rows: [],
    emptyTitle: 'No product performance yet',
    emptyDescription: 'Try another branch or time period to load product analytics.',
  },
  branches: {
    key: 'branches',
    title: 'Branch Performance',
    subtitle: 'Cross-branch comparison for revenue, traffic, and store-level efficiency.',
    description: 'Compare branches using revenue, order count, and growth trends in one workspace.',
    permission: 'view_branch_performance',
    feature: 'analytics_branches',
    chartType: 'doughnut',
    chartTitle: 'Revenue Contribution',
    chartSubtitle: 'Live branch contribution to total revenue.',
    labels: [],
    series: [],
    summaryCards: [],
    branchOptions: [{ label: 'All Branches', value: 'all' }],
    insights: [],
    columns: [],
    rows: [],
    emptyTitle: 'No branch comparison available',
    emptyDescription: 'Branch analytics will appear once multiple locations or channels are active.',
  },
};
