import { Application } from "express";
import { verifyToken } from "../../../middlewares/auth.middleware";
import { checkPermission } from "../../../middlewares/role.middleware";
import { enforceBranchModules } from "../../../middlewares/branch-enforcement.middleware";
import { enforceBillingStatus } from "../../../middlewares/subscription.middleware";
import adminAuthRoutes from "./auth.routes";
import adminAnnouncementRoutes from "./announcement.routes";
import adminOrderRoutes from "./order.routes";
import analyticsRoutes from "./analytics.routes";
import branchRoutes from "./branch.routes";
import searchRoutes from "./search.routes";
import invoiceRoutes from "./invoice.routes";
import customerRoutes from "./customer.routes";
import shopRoutes from "./shop.routes";
import productRoutes from "./product.routes";
import inventoryRoutes from "./inventory.routes";
import offerRoutes from "./offer.routes";
import staffRoutes from "./staff.routes";
import integrationsRoutes from "./integrations.routes";
import mediaRoutes from "./media.routes";
import shiprocketRoutes from "./shiprocket.routes";
import delhiveryRoutes from "./delhivery.routes";
import categoryRoutes from "./category.routes";
import notificationRoutes from "./notification.routes";
import variantRoutes from "./variant.routes";
import promotionsRoutes from "./promotions.routes";
import storageRoutes from "./storage.routes";
import brandRoutes from "./brand.routes";
import returnRoutes from "./return.routes";
import adminRoutes from "./admin.routes";
import observabilityRoutes from "../../../modules/observability/observability.routes";
import subscriptionPlanRoutes from "./subscription-plan.routes";
import platformSettingsRoutes from "./platform-settings.routes";
import dbManagementRoutes from "./db-management.routes";
import costAnalyticsRoutes from "../../../modules/cost-analytics/cost-analytics.routes";
import featureRoutes from "./feature.routes";
import roleRoutes from "./role.routes";
import subscriptionRoutes from "./subscription.routes";
import creditNoteRoutes from "./credit-note.routes";
import customerCreditRoutes from "./customer-credit.routes";
import expenseRoutes from "./expense.routes";
import dailyStockRoutes from "./daily-stock.routes";
import adminLeadRoutes from "./lead.routes";
import supportRoutes from "./support.routes";
import tailorJobCardRoutes from "../../../modules/tailor-job-card/tailor-job-card.routes";
import seasonalCollectionRoutes from "../../../modules/seasonal-collection/seasonal-collection.routes";
import reviewRoutes from "./review.routes";
import accountingRoutes from "./accounting.routes";
import crmRoutes from "./crm.routes";
import purchaseRoutes from "./purchase.routes";
import tailoringRoutes from "./tailoring.routes";
import addonRoutes from "./addon.routes";
import stockTransferRoutes from "./stock-transfer.routes";
import adminNotificationRoutes from "./admin-notification.routes";
import { trackApiUsage } from "../../../middlewares/api-usage.middleware";
import exportRoutes from "../../../modules/export/export.routes";
import walletRoutes from "../../../modules/wallet/wallet.routes";

export const registerAdminApiRoutes = (app: Application) => {
  // Apply API usage tracking globally for all routes under /api/v1
  app.use("/api/v1", trackApiUsage);

  const adminGuards = [verifyToken, checkPermission("admin.access"), enforceBranchModules, enforceBillingStatus];
  const adminBase = "/api/v1/admin";

  app.use(`${adminBase}/auth`, ...adminGuards, adminAuthRoutes);
  app.use(`${adminBase}/announcements`, ...adminGuards, adminAnnouncementRoutes);
  app.use(`${adminBase}/orders`, ...adminGuards, adminOrderRoutes);
  app.use(`${adminBase}/shops`, ...adminGuards, shopRoutes);
  app.use(`${adminBase}/products`, ...adminGuards, productRoutes);
  app.use(`${adminBase}/inventory`, ...adminGuards, inventoryRoutes);
  app.use(`${adminBase}/analytics`, ...adminGuards, analyticsRoutes);
  app.use(`${adminBase}/observability`, ...adminGuards, observabilityRoutes);
  app.use(`${adminBase}/branches`, ...adminGuards, branchRoutes);
  app.use(`${adminBase}/invoices`, ...adminGuards, invoiceRoutes);
  app.use(`${adminBase}/categories`, ...adminGuards, categoryRoutes);
  app.use(`${adminBase}/customers`, ...adminGuards, customerRoutes);
  app.use(`${adminBase}/search`, ...adminGuards, searchRoutes);
  app.use(`${adminBase}/notifications`, ...adminGuards, notificationRoutes);
  app.use(`${adminBase}/variants`, ...adminGuards, variantRoutes);
  app.use(`${adminBase}/offers`, ...adminGuards, offerRoutes);
  app.use(`${adminBase}/shops/:shopId/shiprocket`, ...adminGuards, shiprocketRoutes);
  app.use(`${adminBase}/shops/:shopId/delhivery`, ...adminGuards, delhiveryRoutes);
  app.use(`${adminBase}/shops/:shopId/integrations`, ...adminGuards, integrationsRoutes);
  app.use(`${adminBase}/shops/:shopId/media`, ...adminGuards, mediaRoutes);
  app.use(`${adminBase}/shops/:shopId/storage`, ...adminGuards, storageRoutes);
  app.use(`${adminBase}/promotions`, ...adminGuards, promotionsRoutes);
  app.use(`${adminBase}/brands`, ...adminGuards, brandRoutes);
  app.use(`${adminBase}/staff`, ...adminGuards, staffRoutes);
  app.use(`${adminBase}/returns`, ...adminGuards, returnRoutes);
  app.use(`${adminBase}/credit-notes`, ...adminGuards, creditNoteRoutes);
  app.use(`${adminBase}/customer-credits`, ...adminGuards, customerCreditRoutes);
  app.use(`${adminBase}/expenses`, ...adminGuards, expenseRoutes);
  app.use(`${adminBase}/daily-stock`, ...adminGuards, dailyStockRoutes);
  app.use(`${adminBase}/leads`, ...adminGuards, adminLeadRoutes);
  app.use(`${adminBase}/tailor-job-cards`, ...adminGuards, tailorJobCardRoutes);
  app.use(`${adminBase}/seasonal-collections`, ...adminGuards, seasonalCollectionRoutes);
  app.use(`${adminBase}/reviews`, ...adminGuards, reviewRoutes);
  app.use(`${adminBase}/accounting`, ...adminGuards, accountingRoutes);
  app.use(`${adminBase}/crm`, ...adminGuards, crmRoutes);
  app.use(`${adminBase}/purchases`, ...adminGuards, purchaseRoutes);
  app.use(`${adminBase}/tailoring`, ...adminGuards, tailoringRoutes);
  app.use(`${adminBase}/shops/:shopId/addons`, ...adminGuards, addonRoutes);
  app.use(`${adminBase}/stock-transfers`, ...adminGuards, stockTransferRoutes);
  app.use(`${adminBase}/support`, ...adminGuards, supportRoutes);
  app.use(`${adminBase}/plans`, ...adminGuards, subscriptionPlanRoutes);
  app.use(`${adminBase}/platform`, ...adminGuards, platformSettingsRoutes);
  app.use(`${adminBase}/platform-settings`, ...adminGuards, platformSettingsRoutes); // Alias for legacy/incorrect frontend calls
  app.use(`${adminBase}/db-management`, ...adminGuards, dbManagementRoutes);
  app.use(`${adminBase}/cost-analytics`, ...adminGuards, costAnalyticsRoutes);
  app.use(`${adminBase}`, ...adminGuards, adminRoutes);
  app.use(`${adminBase}/features`, ...adminGuards, featureRoutes);
  app.use(`${adminBase}/roles`, ...adminGuards, roleRoutes);
  app.use(`${adminBase}/subscriptions`, ...adminGuards, subscriptionRoutes);
  app.use(`${adminBase}/exports`, ...adminGuards, exportRoutes);
  app.use(`${adminBase}/wallet`, ...adminGuards, walletRoutes);
  // Admin-only (superadmin) notification system
  app.use("/api/v1/superadmin/notifications", ...adminGuards, adminNotificationRoutes);
  // Public support ticket creation (from shop frontend)
  app.use("/api/v1/support", supportRoutes);
};
