export interface CreditHistoryEntry {
  id?: string;
  amount: number;
  type: 'credit' | 'debit';
  reason: string;
  date: Date;
  referenceId?: string; // e.g. creditNoteId, orderId, or 'manual'
}

export interface CustomerCredit {
  id: string; // usually customerId or customerPhone or autogenerated
  shopId: string;
  customerId: string;
  customerName: string;
  customerPhone?: string;
  customerEmail?: string;
  balance: number;
  history: CreditHistoryEntry[];
  createdAt: Date;
  updatedAt: Date;
}
