import { FeatureDefinition } from "./feature.model";
import { SubscriptionPlan } from "./plan.model";

export const FEATURE_KEYS = {
  // ─── Inventory Module ───
  INV_PRODUCT_LISTING: "inv_product_listing",
  INV_CATEGORIES: "inv_categories",
  INV_STOCK_TRACKING: "inv_stock_tracking",
  INV_STOCK_IN_OUT: "inv_stock_in_out",
  INV_LOW_STOCK_ALERTS: "inv_low_stock_alerts",
  INV_PURCHASE_ORDERS: "inv_purchase_orders",
  INV_SUPPLIERS: "inv_suppliers",
  INV_OPENING_STOCK: "inv_opening_stock",
  INV_STOCK_TRANSFER: "inv_stock_transfer",
  INV_BULK_IMPORT: "inv_bulk_import",
  INV_BRANDS: "inv_brands",
  INV_VARIANTS: "inv_variants",
  INV_BARCODE: "inv_barcode",
  INV_REPORTS: "inv_reports",

  // ─── Selling Module ───
  SELL_POS_BILLING: "sell_pos_billing",
  SELL_INVOICES: "sell_invoices",
  SELL_RETURNS: "sell_returns",
  SELL_DRAFTS: "sell_drafts",
  SELL_DAILY_CLOSING: "sell_daily_closing",
  SELL_CREDIT_NOTES: "sell_credit_notes",
  SELL_CHECKOUT: "sell_checkout",
  SELL_COD: "sell_cod",
  SELL_ONLINE_PAYMENTS: "sell_online_payments",
  SELL_OFFERS_DISCOUNTS: "sell_offers_discounts",
  SELL_OFFLINE_POS_COUNTERS: "sell_offline_pos_counters",

  // ─── Website Module ───
  WEB_STOREFRONT: "web_storefront",
  WEB_THEME: "web_theme",
  WEB_PAGES: "web_pages",
  WEB_DOMAIN: "web_domain",
  WEB_SEO: "web_seo",
  WEB_SETTINGS: "web_settings",
  WEB_AI_BG_REMOVAL: "web_ai_bg_removal",

  // ─── Customer Module ───
  CUST_LIST: "cust_list",
  CUST_ONLINE_CUSTOMERS: "cust_online_customers",
  CUST_CREDITS: "cust_credits",
  CUST_HISTORY: "cust_history",
  CUST_REVIEWS: "cust_reviews",

  // ─── Staff & HR Module ───
  STAFF_MANAGEMENT: "staff_management",
  STAFF_ADD: "staff_add",
  STAFF_COMMISSION: "staff_commission",
  STAFF_LOGS: "staff_logs",
  STAFF_PERFORMANCE: "staff_performance",
  STAFF_ROLE_PERMISSIONS: "staff_role_permissions",

  // ─── Analytics Module ───
  ANALYTICS_DASHBOARD: "analytics_dashboard",
  ANALYTICS_SALES: "analytics_sales",
  ANALYTICS_CUSTOMERS: "analytics_customers",
  ANALYTICS_PRODUCTS: "analytics_products",
  ANALYTICS_BRANCHES: "analytics_branches",

  // ─── Marketing Module ───
  MKTG_PROMOTIONS: "mktg_promotions",
  MKTG_FESTIVAL_OFFERS: "mktg_festival_offers",
  MKTG_LOYALTY: "mktg_loyalty",
  MKTG_SMS: "mktg_sms",
  MKTG_WHATSAPP: "mktg_whatsapp",
  MKTG_TEMPLATES: "mktg_templates",

  // ─── Finance & Accounting Module ───
  FIN_TRANSACTIONS: "fin_transactions",
  FIN_EXPENSES: "fin_expenses",
  FIN_PAYMENTS: "fin_payments",
  FIN_PNL_REPORT: "fin_pnl_report",
  FIN_TAX_REPORT: "fin_tax_report",
  ACC_CASH_BOOK: "acc_cash_book",
  ACC_BANK_BOOK: "acc_bank_book",
  ACC_LEDGER: "acc_ledger",
  ACC_RECEIVABLES: "acc_receivables",
  ACC_PAYABLES: "acc_payables",

  // ─── CRM Module ───
  CRM_BIRTHDAY_WISHES: "crm_birthday_wishes",
  CRM_CUSTOMER_SEGMENTATION: "crm_customer_segmentation",
  CRM_VIP_LEADERBOARD: "crm_vip_leaderboard",

  // ─── Shipping Module ───
  SHIP_SETUP: "ship_setup",
  SHIP_SHIPROCKET: "ship_shiprocket",
  SHIP_TRACKING: "ship_tracking",

  // ─── Integrations Module ───
  INTG_API_ACCESS: "intg_api_access",
  INTG_PAYMENT_GATEWAY: "intg_payment_gateway",
  INTG_INVOICE_TEMPLATE: "intg_invoice_template",

  // ─── Enterprise Module ───
  ENT_MULTI_BRANCH: "ent_multi_branch",
  ENT_CUSTOM_BRANDING: "ent_custom_branding",
  ENT_AUDIT_LOGS: "ent_audit_logs",
  ENT_SECURITY: "ent_security",
  ENT_BACKUP: "ent_backup",

  // ─── Custom Boutique / E-commerce Features ───
  INV_COLOR_INVENTORY: "inv_color_inventory",
  TAILOR_JOB_CARDS: "tailor_job_cards",
  SEASONAL_COLLECTIONS: "seasonal_collections",
  WHOLESALE_SYSTEM: "wholesale_system",
} as const;

export const LIMIT_KEYS = {
  ORDERS_PER_MONTH: "orders_per_month",
  SMS_PER_MONTH: "sms_per_month",
  STAFF_COUNT: "staff_count",
  BRANCH_COUNT: "branch_count",
  PRODUCTS_COUNT: "products_count",
  INVOICES_PER_MONTH: "invoices_per_month",
  STORAGE_LIMIT_MB: "storage_limit_mb",
  OFFLINE_POS_COUNTERS_COUNT: "offline_pos_counters_count",
} as const;

export const DEFAULT_FEATURES: FeatureDefinition[] = [
  // ─── Inventory ───
  { key: FEATURE_KEYS.INV_PRODUCT_LISTING,  label: "Product Listing",       category: "inventory",    description: "View and manage product list.",                    active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_CATEGORIES,       label: "Categories",            category: "inventory",    description: "Manage product categories.",                       active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_STOCK_TRACKING,   label: "Stock Tracking",        category: "inventory",    description: "Track real-time stock levels.",                    active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_STOCK_IN_OUT,     label: "Stock In / Out",        category: "inventory",    description: "Manual stock adjustments.",                        active: false, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_LOW_STOCK_ALERTS, label: "Low Stock Alerts",      category: "inventory",    description: "Get alerts when stock falls below threshold.",     active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_PURCHASE_ORDERS,  label: "Purchase Orders",       category: "inventory",    description: "Create and manage purchase orders to suppliers.",  active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_SUPPLIERS,        label: "Suppliers",             category: "inventory",    description: "Manage supplier directory.",                       active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_OPENING_STOCK,    label: "Opening Stock",         category: "inventory",    description: "Set initial stock values.",                        active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_STOCK_TRANSFER,   label: "Stock Transfer",        category: "inventory",    description: "Transfer stock between branches.",                 active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_BULK_IMPORT,      label: "Bulk Product Import",   category: "inventory",    description: "Import products via CSV/Excel.",                   active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_BRANDS,           label: "Brands Management",     category: "inventory",    description: "Organize products by brand.",                      active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_VARIANTS,         label: "Product Variants",      category: "inventory",    description: "Size, color, and other variant support.",          active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_BARCODE,          label: "Barcode Support",       category: "inventory",    description: "Generate and scan barcodes for products.",         active: false, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INV_REPORTS,          label: "Inventory Reports",     category: "inventory",    description: "Stock movement and valuation reports.",            active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Selling ───
  { key: FEATURE_KEYS.SELL_POS_BILLING,     label: "POS Billing",           category: "selling",      description: "Point of sale billing system.",                    active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_INVOICES,        label: "Invoices",              category: "selling",      description: "Create and send invoices.",                        active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_RETURNS,         label: "Sales Returns",         category: "selling",      description: "Process return and refund.",                       active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_DRAFTS,          label: "Draft Orders",          category: "selling",      description: "Save draft orders for later.",                     active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_DAILY_CLOSING,   label: "Daily Closing",         category: "selling",      description: "End-of-day cash closing.",                         active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_CREDIT_NOTES,    label: "Credit Notes",          category: "selling",      description: "Issue store credit notes.",                        active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_CHECKOUT,        label: "Online Checkout",       category: "selling",      description: "Customers can place orders from website.",         active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_COD,             label: "Cash on Delivery",      category: "selling",      description: "Allow COD payment method.",                        active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_ONLINE_PAYMENTS, label: "Online Payments",       category: "selling",      description: "Accept online payments.",                          active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_OFFLINE_POS_COUNTERS, label: "Offline POS Counters", category: "selling", description: "Allow merchants to connect multiple offline desktop POS applications using secure API authentication.", active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SELL_OFFERS_DISCOUNTS,label: "Offers & Discounts",    category: "selling",      description: "Create offers, coupons, discounts.",               active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Website ───
  { key: FEATURE_KEYS.WEB_STOREFRONT,       label: "Storefront Website",    category: "website",      description: "Public storefront for products.",                  active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.WEB_THEME,            label: "Theme Customization",   category: "website",      description: "Customize storefront theme.",                      active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.WEB_PAGES,            label: "Custom Pages",          category: "website",      description: "Create custom pages (About, Contact).",            active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.WEB_DOMAIN,           label: "Custom Domain",         category: "website",      description: "Use your own domain name.",                        active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.WEB_SEO,              label: "SEO Tools",             category: "website",      description: "Search engine optimization tools.",                active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.WEB_SETTINGS,         label: "Website Settings",      category: "website",      description: "Advanced website configuration.",                  active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.WEB_AI_BG_REMOVAL,    label: "Ai Auto Backround removal", category: "website",      description: "AI-powered automated image background removal tool.", active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Customers ───
  { key: FEATURE_KEYS.CUST_LIST,            label: "Customer List",         category: "customers",    description: "View and manage customers.",                       active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.CUST_ONLINE_CUSTOMERS,label: "Online Customers",      category: "customers",    description: "Track website-registered customers.",              active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.CUST_CREDITS,         label: "Customer Credits",      category: "customers",    description: "Manage store credit for customers.",               active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.CUST_HISTORY,         label: "Purchase History",      category: "customers",    description: "View customer purchase history.",                   active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.CUST_REVIEWS,         label: "Customer Reviews",      category: "customers",    description: "Manage product reviews from customers.",           active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Staff & HR ───
  { key: FEATURE_KEYS.STAFF_MANAGEMENT,     label: "Staff Management",      category: "staff",        description: "Add and manage staff members.",                    active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.STAFF_ADD,            label: "Add Staff",             category: "staff",        description: "Invite and add new staff members.",                active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.STAFF_COMMISSION,     label: "Staff Commission",      category: "staff",        description: "Track and calculate staff commission.",            active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.STAFF_LOGS,           label: "Staff Logs",            category: "staff",        description: "View staff activity logs.",                        active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.STAFF_PERFORMANCE,    label: "Staff Performance",     category: "staff",        description: "Staff performance analytics.",                     active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.STAFF_ROLE_PERMISSIONS,label: "Role Permissions",     category: "staff",        description: "Custom roles and permission mapping.",             active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Analytics ───
  { key: FEATURE_KEYS.ANALYTICS_DASHBOARD,  label: "Analytics Dashboard",   category: "analytics",    description: "Main analytics overview.",                         active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ANALYTICS_SALES,      label: "Sales Analytics",       category: "analytics",    description: "Detailed sales analytics.",                        active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ANALYTICS_CUSTOMERS,  label: "Customer Analytics",    category: "analytics",    description: "Customer behavior analytics.",                     active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ANALYTICS_PRODUCTS,   label: "Product Analytics",     category: "analytics",    description: "Product performance analytics.",                   active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ANALYTICS_BRANCHES,   label: "Branch Analytics",      category: "analytics",    description: "Multi-branch performance comparison.",             active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Marketing ───
  { key: FEATURE_KEYS.MKTG_PROMOTIONS,      label: "Promotions",            category: "marketing",    description: "Create and manage promotions.",                    active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.MKTG_FESTIVAL_OFFERS, label: "Festival Offers",       category: "marketing",    description: "Festival-based promotional offers.",               active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.MKTG_LOYALTY,         label: "Loyalty Programme",     category: "marketing",    description: "Customer loyalty and rewards program.",            active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.MKTG_SMS,             label: "SMS Campaigns",         category: "marketing",    description: "Send bulk SMS campaigns.",                         active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.MKTG_WHATSAPP,        label: "WhatsApp Campaigns",    category: "marketing",    description: "Send WhatsApp promotional messages.",              active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.MKTG_TEMPLATES,       label: "Message Templates",     category: "marketing",    description: "Reusable message templates.",                      active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Finance ───
  { key: FEATURE_KEYS.FIN_TRANSACTIONS,     label: "Transactions",          category: "finance",      description: "View all transactions.",                           active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.FIN_EXPENSES,         label: "Expense Tracking",      category: "finance",      description: "Track and categorize expenses.",                   active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.FIN_PAYMENTS,         label: "Payment Management",    category: "finance",      description: "Manage payment methods and records.",              active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.FIN_PNL_REPORT,       label: "P&L Report",            category: "finance",      description: "Profit and loss report.",                          active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.FIN_TAX_REPORT,       label: "Tax Report",            category: "finance",      description: "GST/Tax reports.",                                 active: true, createdAt: new Date(), updatedAt: new Date() },
  
  // ─── Accounting ───
  { key: FEATURE_KEYS.ACC_CASH_BOOK,        label: "Cash Book",             category: "accounting",   description: "Manage and audit cash transactions.",              active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ACC_BANK_BOOK,        label: "Bank Book",             category: "accounting",   description: "Track bank transactions and reconciliations.",     active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ACC_LEDGER,           label: "General Ledger",        category: "accounting",   description: "Unified double-entry financial ledger.",            active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ACC_RECEIVABLES,      label: "Accounts Receivable",   category: "accounting",   description: "Track customer outstanding balances.",              active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ACC_PAYABLES,         label: "Accounts Payable",      category: "accounting",   description: "Track supplier outstanding balances.",              active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── CRM ───
  { key: FEATURE_KEYS.CRM_BIRTHDAY_WISHES,   label: "Birthday Wishes",       category: "crm",          description: "Celebrate birthdays and auto-send custom offers.", active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.CRM_CUSTOMER_SEGMENTATION, label: "Customer Segmentation", category: "crm",        description: "Group customers based on spending and activity.",  active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.CRM_VIP_LEADERBOARD,   label: "VIP Leaderboard",       category: "crm",          description: "Identify and reward high-value VIP customers.",    active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Shipping ───
  { key: FEATURE_KEYS.SHIP_SETUP,           label: "Shipping Setup",        category: "shipping",     description: "Configure shipping methods.",                      active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SHIP_SHIPROCKET,      label: "Shiprocket Integration",category: "shipping",     description: "Shiprocket integration for shipping.",             active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SHIP_TRACKING,        label: "Shipment Tracking",     category: "shipping",     description: "Track shipments in real-time.",                    active: false, createdAt: new Date(), updatedAt: new Date() },

  // ─── Integrations ───
  { key: FEATURE_KEYS.INTG_API_ACCESS,      label: "API Access",            category: "integrations", description: "REST API access to platform.",                     active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INTG_PAYMENT_GATEWAY, label: "Payment Gateway",       category: "integrations", description: "Payment gateway integrations.",                    active: false, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.INTG_INVOICE_TEMPLATE,label: "Invoice Templates",     category: "integrations", description: "Custom invoice template designs.",                 active: true, createdAt: new Date(), updatedAt: new Date() },

  // ─── Enterprise ───
  { key: FEATURE_KEYS.ENT_MULTI_BRANCH,     label: "Multi Branch",          category: "enterprise",   description: "Multi-location branch management.",                active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ENT_CUSTOM_BRANDING,  label: "Custom Branding",       category: "enterprise",   description: "White-label and custom branding.",                 active: false, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ENT_AUDIT_LOGS,       label: "Audit Logs",            category: "enterprise",   description: "System audit trail and logs.",                     active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ENT_SECURITY,         label: "Advanced Security",     category: "enterprise",   description: "Advanced security features.",                      active: false, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.ENT_BACKUP,           label: "Data Backup",           category: "enterprise",   description: "Automated data backup.",                           active: false, createdAt: new Date(), updatedAt: new Date() },

  // ─── Custom Boutique / E-commerce Features ───
  { key: FEATURE_KEYS.INV_COLOR_INVENTORY,  label: "Color-wise Inventory",  category: "inventory",    description: "Maintain and track inventory separate by product colors.", active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.TAILOR_JOB_CARDS,     label: "Tailor Job Cards",      category: "staff",        description: "Assign daily work, manage statuses, and track tailor performance.", active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.SEASONAL_COLLECTIONS, label: "Seasonal Collections",  category: "inventory",    description: "Organize products by seasonal collections (Summer, Winter, Festive).", active: true, createdAt: new Date(), updatedAt: new Date() },
  { key: FEATURE_KEYS.WHOLESALE_SYSTEM,     label: "Wholesale System",      category: "selling",      description: "Manage wholesale B2B pricing, billing rules, and wholesaler catalog.", active: true, createdAt: new Date(), updatedAt: new Date() },
];

export const DEFAULT_PLANS: SubscriptionPlan[] = [
  {
    id: "trial",
    code: "trial",
    name: "5-Day Free Trial",
    description: "Full access to all Pro features for 5 days.",
    price: 0,
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: "INR",
    features: [
      // Inventory — everything
      FEATURE_KEYS.INV_PRODUCT_LISTING,
      FEATURE_KEYS.INV_CATEGORIES,
      FEATURE_KEYS.INV_STOCK_TRACKING,
      FEATURE_KEYS.INV_STOCK_IN_OUT,
      FEATURE_KEYS.INV_LOW_STOCK_ALERTS,
      FEATURE_KEYS.INV_PURCHASE_ORDERS,
      FEATURE_KEYS.INV_SUPPLIERS,
      FEATURE_KEYS.INV_OPENING_STOCK,
      FEATURE_KEYS.INV_STOCK_TRANSFER,
      FEATURE_KEYS.INV_BULK_IMPORT,
      FEATURE_KEYS.INV_BRANDS,
      FEATURE_KEYS.INV_VARIANTS,
      FEATURE_KEYS.INV_BARCODE,
      FEATURE_KEYS.INV_REPORTS,
      FEATURE_KEYS.INV_COLOR_INVENTORY,
      FEATURE_KEYS.SEASONAL_COLLECTIONS,
      // Selling — everything
      FEATURE_KEYS.SELL_POS_BILLING,
      FEATURE_KEYS.SELL_INVOICES,
      FEATURE_KEYS.SELL_RETURNS,
      FEATURE_KEYS.SELL_DRAFTS,
      FEATURE_KEYS.SELL_DAILY_CLOSING,
      FEATURE_KEYS.SELL_CREDIT_NOTES,
      FEATURE_KEYS.SELL_CHECKOUT,
      FEATURE_KEYS.SELL_COD,
      FEATURE_KEYS.SELL_ONLINE_PAYMENTS,
      FEATURE_KEYS.SELL_OFFERS_DISCOUNTS,
      FEATURE_KEYS.SELL_OFFLINE_POS_COUNTERS,
      // Website — everything
      FEATURE_KEYS.WEB_STOREFRONT,
      FEATURE_KEYS.WEB_THEME,
      FEATURE_KEYS.WEB_PAGES,
      FEATURE_KEYS.WEB_DOMAIN,
      FEATURE_KEYS.WEB_SEO,
      FEATURE_KEYS.WEB_SETTINGS,
      FEATURE_KEYS.WEB_AI_BG_REMOVAL,
      // Customer — everything
      FEATURE_KEYS.CUST_LIST,
      FEATURE_KEYS.CUST_ONLINE_CUSTOMERS,
      FEATURE_KEYS.CUST_CREDITS,
      FEATURE_KEYS.CUST_HISTORY,
      FEATURE_KEYS.CUST_REVIEWS,
      // Staff — everything
      FEATURE_KEYS.STAFF_MANAGEMENT,
      FEATURE_KEYS.STAFF_ADD,
      FEATURE_KEYS.STAFF_COMMISSION,
      FEATURE_KEYS.STAFF_LOGS,
      FEATURE_KEYS.STAFF_PERFORMANCE,
      FEATURE_KEYS.STAFF_ROLE_PERMISSIONS,
      FEATURE_KEYS.TAILOR_JOB_CARDS,
      // Analytics — all
      FEATURE_KEYS.ANALYTICS_DASHBOARD,
      FEATURE_KEYS.ANALYTICS_SALES,
      FEATURE_KEYS.ANALYTICS_CUSTOMERS,
      FEATURE_KEYS.ANALYTICS_PRODUCTS,
      FEATURE_KEYS.ANALYTICS_BRANCHES,
      // Marketing — all
      FEATURE_KEYS.MKTG_PROMOTIONS,
      FEATURE_KEYS.MKTG_FESTIVAL_OFFERS,
      FEATURE_KEYS.MKTG_LOYALTY,
      FEATURE_KEYS.MKTG_SMS,
      FEATURE_KEYS.MKTG_WHATSAPP,
      FEATURE_KEYS.MKTG_TEMPLATES,
      // CRM — all
      FEATURE_KEYS.CRM_BIRTHDAY_WISHES,
      FEATURE_KEYS.CRM_CUSTOMER_SEGMENTATION,
      FEATURE_KEYS.CRM_VIP_LEADERBOARD,
      // Finance — all
      FEATURE_KEYS.FIN_TRANSACTIONS,
      FEATURE_KEYS.FIN_EXPENSES,
      FEATURE_KEYS.FIN_PAYMENTS,
      FEATURE_KEYS.FIN_PNL_REPORT,
      FEATURE_KEYS.FIN_TAX_REPORT,
      // Accounting — all
      FEATURE_KEYS.ACC_CASH_BOOK,
      FEATURE_KEYS.ACC_BANK_BOOK,
      FEATURE_KEYS.ACC_LEDGER,
      FEATURE_KEYS.ACC_RECEIVABLES,
      FEATURE_KEYS.ACC_PAYABLES,
      // Shipping — all
      FEATURE_KEYS.SHIP_SETUP,
      FEATURE_KEYS.SHIP_SHIPROCKET,
      FEATURE_KEYS.SHIP_TRACKING,
      // Integrations
      FEATURE_KEYS.INTG_API_ACCESS,
      FEATURE_KEYS.INTG_PAYMENT_GATEWAY,
      FEATURE_KEYS.INTG_INVOICE_TEMPLATE,
      FEATURE_KEYS.WHOLESALE_SYSTEM,
      // Enterprise — multi branch
      FEATURE_KEYS.ENT_MULTI_BRANCH,
    ],
    limits: {
      [LIMIT_KEYS.ORDERS_PER_MONTH]: 100,
      [LIMIT_KEYS.SMS_PER_MONTH]: 50,
      [LIMIT_KEYS.STAFF_COUNT]: 5,
      [LIMIT_KEYS.BRANCH_COUNT]: 1,
      [LIMIT_KEYS.PRODUCTS_COUNT]: 1000,
      [LIMIT_KEYS.INVOICES_PER_MONTH]: 100,
      [LIMIT_KEYS.STORAGE_LIMIT_MB]: 500,
      [LIMIT_KEYS.OFFLINE_POS_COUNTERS_COUNT]: 2,
    },
    includedStorageMB: 500,
    includedStorageBytes: 524288000,
    storageUnit: "MB",
    storageDisplay: "500 MB",
    badge: "Trial",
    targetAudience: "New shop owners",
    capabilityLabel: "Full Access",
    icon: "clock",
    color: "#3b82f6",
    bgColor: "#eff6ff",
    featured: false,
    active: false, // Hidden from normal listing
    sortOrder: 1,
    limitations: [],
    metadata: {
      autoPayEligible: false,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "plus",
    code: "plus",
    name: "Plus",
    description: "Growth plan for shops that want a branded showcase.",
    price: 999,
    monthlyPrice: 999,
    yearlyPrice: 9990,
    currency: "INR",
    features: [
      // Inventory — full basic + advanced catalog
      FEATURE_KEYS.INV_PRODUCT_LISTING,
      FEATURE_KEYS.INV_CATEGORIES,
      FEATURE_KEYS.INV_STOCK_TRACKING,
      FEATURE_KEYS.INV_STOCK_IN_OUT,
      FEATURE_KEYS.INV_LOW_STOCK_ALERTS,
      FEATURE_KEYS.INV_PURCHASE_ORDERS,
      FEATURE_KEYS.INV_SUPPLIERS,
      FEATURE_KEYS.INV_OPENING_STOCK,
      FEATURE_KEYS.INV_BULK_IMPORT,
      FEATURE_KEYS.INV_BRANDS,
      FEATURE_KEYS.INV_VARIANTS,
      FEATURE_KEYS.INV_BARCODE,
      FEATURE_KEYS.INV_COLOR_INVENTORY,
      FEATURE_KEYS.SEASONAL_COLLECTIONS,
      // Selling — extended
      FEATURE_KEYS.SELL_POS_BILLING,
      FEATURE_KEYS.SELL_INVOICES,
      FEATURE_KEYS.SELL_RETURNS,
      FEATURE_KEYS.SELL_DRAFTS,
      FEATURE_KEYS.SELL_DAILY_CLOSING,
      FEATURE_KEYS.SELL_COD,
      FEATURE_KEYS.SELL_OFFERS_DISCOUNTS,
      // Website — basic storefront
      FEATURE_KEYS.WEB_STOREFRONT,
      FEATURE_KEYS.WEB_THEME,
      FEATURE_KEYS.WEB_PAGES,
      FEATURE_KEYS.WEB_DOMAIN,
      // Customer — extended
      FEATURE_KEYS.CUST_LIST,
      FEATURE_KEYS.CUST_ONLINE_CUSTOMERS,
      FEATURE_KEYS.CUST_CREDITS,
      FEATURE_KEYS.CUST_HISTORY,
      // Staff — basic
      FEATURE_KEYS.STAFF_MANAGEMENT,
      FEATURE_KEYS.STAFF_ADD,
      FEATURE_KEYS.STAFF_COMMISSION,
      // Finance — basic
      FEATURE_KEYS.FIN_TRANSACTIONS,
      FEATURE_KEYS.FIN_EXPENSES,
      FEATURE_KEYS.FIN_PAYMENTS,
      // Accounting — basic
      FEATURE_KEYS.ACC_CASH_BOOK,
      FEATURE_KEYS.ACC_BANK_BOOK,
      // Marketing — basic
      FEATURE_KEYS.MKTG_PROMOTIONS,
      FEATURE_KEYS.MKTG_FESTIVAL_OFFERS,
      FEATURE_KEYS.MKTG_LOYALTY,
      FEATURE_KEYS.MKTG_TEMPLATES,
      // CRM — basic
      FEATURE_KEYS.CRM_BIRTHDAY_WISHES,
      FEATURE_KEYS.CRM_CUSTOMER_SEGMENTATION,
      // Shipping — basic
      FEATURE_KEYS.SHIP_SETUP,
      FEATURE_KEYS.SHIP_SHIPROCKET,
      // Analytics - basic
      FEATURE_KEYS.ANALYTICS_DASHBOARD,
    ],
    limits: {
      [LIMIT_KEYS.ORDERS_PER_MONTH]: 500,
      [LIMIT_KEYS.SMS_PER_MONTH]: 100,
      [LIMIT_KEYS.STAFF_COUNT]: 5,
      [LIMIT_KEYS.BRANCH_COUNT]: 1,
      [LIMIT_KEYS.PRODUCTS_COUNT]: 5000,
      [LIMIT_KEYS.INVOICES_PER_MONTH]: 500,
      [LIMIT_KEYS.STORAGE_LIMIT_MB]: 500,
      [LIMIT_KEYS.OFFLINE_POS_COUNTERS_COUNT]: 2,
    },
    includedStorageMB: 500,
    includedStorageBytes: 524288000,
    storageUnit: "MB",
    storageDisplay: "500 MB",
    badge: "Growth",
    targetAudience: "Growing retailers",
    capabilityLabel: "Showcase Website",
    icon: "sparkles",
    color: "#16a34a",
    bgColor: "#f0fdf4",
    featured: true,
    active: true,
    sortOrder: 2,
    limitations: ["No full checkout", "No advanced analytics", "No API access"],
    metadata: {
      autoPayEligible: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "pro",
    code: "pro",
    name: "Pro",
    description: "Full commerce plan for fast-growing online sellers.",
    price: 1999,
    monthlyPrice: 1999,
    yearlyPrice: 19990,
    currency: "INR",
    features: [
      // Inventory — everything
      FEATURE_KEYS.INV_PRODUCT_LISTING,
      FEATURE_KEYS.INV_CATEGORIES,
      FEATURE_KEYS.INV_STOCK_TRACKING,
      FEATURE_KEYS.INV_STOCK_IN_OUT,
      FEATURE_KEYS.INV_LOW_STOCK_ALERTS,
      FEATURE_KEYS.INV_PURCHASE_ORDERS,
      FEATURE_KEYS.INV_SUPPLIERS,
      FEATURE_KEYS.INV_OPENING_STOCK,
      FEATURE_KEYS.INV_STOCK_TRANSFER,
      FEATURE_KEYS.INV_BULK_IMPORT,
      FEATURE_KEYS.INV_BRANDS,
      FEATURE_KEYS.INV_VARIANTS,
      FEATURE_KEYS.INV_BARCODE,
      FEATURE_KEYS.INV_REPORTS,
      FEATURE_KEYS.INV_COLOR_INVENTORY,
      FEATURE_KEYS.SEASONAL_COLLECTIONS,
      // Selling — everything
      FEATURE_KEYS.SELL_POS_BILLING,
      FEATURE_KEYS.SELL_INVOICES,
      FEATURE_KEYS.SELL_RETURNS,
      FEATURE_KEYS.SELL_DRAFTS,
      FEATURE_KEYS.SELL_DAILY_CLOSING,
      FEATURE_KEYS.SELL_CREDIT_NOTES,
      FEATURE_KEYS.SELL_CHECKOUT,
      FEATURE_KEYS.SELL_COD,
      FEATURE_KEYS.SELL_ONLINE_PAYMENTS,
      FEATURE_KEYS.SELL_OFFERS_DISCOUNTS,
      // Website — everything
      FEATURE_KEYS.WEB_STOREFRONT,
      FEATURE_KEYS.WEB_THEME,
      FEATURE_KEYS.WEB_PAGES,
      FEATURE_KEYS.WEB_DOMAIN,
      FEATURE_KEYS.WEB_SEO,
      FEATURE_KEYS.WEB_SETTINGS,
      FEATURE_KEYS.WEB_AI_BG_REMOVAL,
      // Customer — everything
      FEATURE_KEYS.CUST_LIST,
      FEATURE_KEYS.CUST_ONLINE_CUSTOMERS,
      FEATURE_KEYS.CUST_CREDITS,
      FEATURE_KEYS.CUST_HISTORY,
      FEATURE_KEYS.CUST_REVIEWS,
      // Staff — everything
      FEATURE_KEYS.STAFF_MANAGEMENT,
      FEATURE_KEYS.STAFF_ADD,
      FEATURE_KEYS.STAFF_COMMISSION,
      FEATURE_KEYS.STAFF_LOGS,
      FEATURE_KEYS.STAFF_PERFORMANCE,
      FEATURE_KEYS.STAFF_ROLE_PERMISSIONS,
      FEATURE_KEYS.TAILOR_JOB_CARDS,
      // Analytics — all
      FEATURE_KEYS.ANALYTICS_DASHBOARD,
      FEATURE_KEYS.ANALYTICS_SALES,
      FEATURE_KEYS.ANALYTICS_CUSTOMERS,
      FEATURE_KEYS.ANALYTICS_PRODUCTS,
      FEATURE_KEYS.ANALYTICS_BRANCHES,
      // Marketing — all
      FEATURE_KEYS.MKTG_PROMOTIONS,
      FEATURE_KEYS.MKTG_FESTIVAL_OFFERS,
      FEATURE_KEYS.MKTG_LOYALTY,
      FEATURE_KEYS.MKTG_SMS,
      FEATURE_KEYS.MKTG_WHATSAPP,
      FEATURE_KEYS.MKTG_TEMPLATES,
      // CRM — all
      FEATURE_KEYS.CRM_BIRTHDAY_WISHES,
      FEATURE_KEYS.CRM_CUSTOMER_SEGMENTATION,
      FEATURE_KEYS.CRM_VIP_LEADERBOARD,
      // Finance — all
      FEATURE_KEYS.FIN_TRANSACTIONS,
      FEATURE_KEYS.FIN_EXPENSES,
      FEATURE_KEYS.FIN_PAYMENTS,
      FEATURE_KEYS.FIN_PNL_REPORT,
      FEATURE_KEYS.FIN_TAX_REPORT,
      // Accounting — all
      FEATURE_KEYS.ACC_CASH_BOOK,
      FEATURE_KEYS.ACC_BANK_BOOK,
      FEATURE_KEYS.ACC_LEDGER,
      FEATURE_KEYS.ACC_RECEIVABLES,
      FEATURE_KEYS.ACC_PAYABLES,
      // Shipping — all
      FEATURE_KEYS.SHIP_SETUP,
      FEATURE_KEYS.SHIP_SHIPROCKET,
      FEATURE_KEYS.SHIP_TRACKING,
      // Integrations
      FEATURE_KEYS.INTG_API_ACCESS,
      FEATURE_KEYS.INTG_PAYMENT_GATEWAY,
      FEATURE_KEYS.INTG_INVOICE_TEMPLATE,
      FEATURE_KEYS.WHOLESALE_SYSTEM,
      // Enterprise — multi branch
      FEATURE_KEYS.ENT_MULTI_BRANCH,
    ],
    limits: {
      [LIMIT_KEYS.ORDERS_PER_MONTH]: null,
      [LIMIT_KEYS.SMS_PER_MONTH]: 200,
      [LIMIT_KEYS.STAFF_COUNT]: 20,
      [LIMIT_KEYS.BRANCH_COUNT]: 5,
      [LIMIT_KEYS.PRODUCTS_COUNT]: null,
      [LIMIT_KEYS.INVOICES_PER_MONTH]: null,
      [LIMIT_KEYS.STORAGE_LIMIT_MB]: 2048,
      [LIMIT_KEYS.OFFLINE_POS_COUNTERS_COUNT]: 5,
    },
    includedStorageMB: 2048,
    includedStorageBytes: 2147483648,
    storageUnit: "GB",
    storageDisplay: "2 GB",
    badge: "Most Popular",
    targetAudience: "Scaling brands",
    capabilityLabel: "Full Online Selling",
    icon: "rocket",
    color: "#9333ea",
    bgColor: "#faf5ff",
    featured: false,
    active: true,
    sortOrder: 3,
    limitations: [],
    metadata: {
      autoPayEligible: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "custom",
    code: "custom",
    name: "Enterprise",
    description: "Enterprise-grade setup for multi-store and white-label needs.",
    price: null,
    monthlyPrice: null,
    yearlyPrice: null,
    currency: "INR",
    features: [],
    limits: {
      [LIMIT_KEYS.ORDERS_PER_MONTH]: null,
      [LIMIT_KEYS.SMS_PER_MONTH]: null,
      [LIMIT_KEYS.STAFF_COUNT]: null,
      [LIMIT_KEYS.BRANCH_COUNT]: null,
      [LIMIT_KEYS.PRODUCTS_COUNT]: null,
      [LIMIT_KEYS.INVOICES_PER_MONTH]: null,
      [LIMIT_KEYS.STORAGE_LIMIT_MB]: 10240,
      [LIMIT_KEYS.OFFLINE_POS_COUNTERS_COUNT]: null,
    },
    includedStorageMB: 10240,
    includedStorageBytes: 10737418240,
    storageUnit: "GB",
    storageDisplay: "10 GB",
    badge: "Enterprise",
    targetAudience: "Retail chains and enterprises",
    capabilityLabel: "Custom Scale",
    icon: "building",
    color: "#ea580c",
    bgColor: "#fff7ed",
    featured: false,
    active: true,
    sortOrder: 4,
    limitations: [],
    metadata: {
      autoPayEligible: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
