import * as ExcelJS from 'exceljs';
import { ExportHistoryRecord } from '../export.model';
import { ReportDataResult } from './report-data-fetcher.service';

export class ExcelReportBuilder {
  
  static async build(record: ExportHistoryRecord, dataResult: ReportDataResult, targetPath: string): Promise<void> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'DashKit Enterprise Reporting Engine';
    workbook.created = new Date();

    // ── SHEET 1: Executive Summary & Metadata ─────────────────────────────────────
    const summarySheet = workbook.addWorksheet('Executive Summary');
    summarySheet.views = [{ showGridLines: true }];

    // Header Title
    summarySheet.mergeCells('A1:F2');
    const titleCell = summarySheet.getCell('A1');
    titleCell.value = dataResult.title;
    titleCell.font = { name: 'Calibri', size: 16, bold: true, color: { argb: 'FFFFFFFF' } };
    titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F172A' } }; // Slate 900
    titleCell.alignment = { vertical: 'middle', horizontal: 'center' };

    // Description
    summarySheet.mergeCells('A3:F3');
    const descCell = summarySheet.getCell('A3');
    descCell.value = dataResult.description;
    descCell.font = { name: 'Calibri', size: 11, italic: true, color: { argb: 'FF475569' } };
    descCell.alignment = { vertical: 'middle', horizontal: 'left' };

    // Metadata Block
    const metaStartRow = 5;
    const filtersStr = record.filters ? JSON.stringify(record.filters) : 'None';
    const metadata = [
      ['Report Name:', record.name, 'Generated Date & Time:', new Date().toLocaleString('en-IN')],
      ['Generated By:', record.requestedByName || 'Super Admin', 'Total Records:', dataResult.totalRecords],
      ['Date Range:', `${record.filters?.startDate || 'All Time'} to ${record.filters?.endDate || 'Present'}`, 'Applied Filters:', filtersStr],
    ];

    metadata.forEach((row, idx) => {
      const rIdx = metaStartRow + idx;
      summarySheet.getCell(`A${rIdx}`).value = row[0];
      summarySheet.getCell(`A${rIdx}`).font = { bold: true, color: { argb: 'FF334155' } };
      summarySheet.getCell(`B${rIdx}`).value = row[1];

      summarySheet.getCell(`D${rIdx}`).value = row[2];
      summarySheet.getCell(`D${rIdx}`).font = { bold: true, color: { argb: 'FF334155' } };
      summarySheet.getCell(`E${rIdx}`).value = row[3];
    });

    // KPI Summary Section
    let kpiRow = 10;
    summarySheet.getCell(`A${kpiRow}`).value = 'EXECUTIVE SUMMARY KPI METRICS';
    summarySheet.getCell(`A${kpiRow}`).font = { bold: true, size: 12, color: { argb: 'FF4F46E5' } };

    kpiRow += 2;
    dataResult.kpis.forEach((kpi) => {
      summarySheet.getCell(`A${kpiRow}`).value = kpi.label;
      summarySheet.getCell(`A${kpiRow}`).font = { bold: true, color: { argb: 'FF1E293B' } };

      summarySheet.getCell(`B${kpiRow}`).value = kpi.value;
      summarySheet.getCell(`B${kpiRow}`).font = { bold: true, size: 12, color: { argb: 'FF059669' } };

      if (kpi.subtext) {
        summarySheet.getCell(`C${kpiRow}`).value = kpi.subtext;
        summarySheet.getCell(`C${kpiRow}`).font = { italic: true, color: { argb: 'FF64748B' } };
      }
      kpiRow++;
    });

    // Set column widths for summary sheet
    summarySheet.getColumn('A').width = 25;
    summarySheet.getColumn('B').width = 30;
    summarySheet.getColumn('C').width = 30;
    summarySheet.getColumn('D').width = 25;
    summarySheet.getColumn('E').width = 30;
    summarySheet.getColumn('F').width = 20;

    // ── SHEET 2+: Data Tables ──────────────────────────────────────────────────────
    dataResult.tables.forEach((table) => {
      const sheet = workbook.addWorksheet(table.sheetName.substring(0, 31));
      sheet.views = [{ showGridLines: true }];

      // Sheet Header Title
      sheet.mergeCells(1, 1, 1, table.columns.length || 1);
      const sTitle = sheet.getCell(1, 1);
      sTitle.value = table.title;
      sTitle.font = { name: 'Calibri', size: 14, bold: true, color: { argb: 'FFFFFFFF' } };
      sTitle.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E293B' } };
      sTitle.alignment = { vertical: 'middle', horizontal: 'left' };

      const headerRowIndex = 3;
      const colKeys = table.columns.map(c => c.key);

      // Add Headers
      table.columns.forEach((col, idx) => {
        const cell = sheet.getCell(headerRowIndex, idx + 1);
        cell.value = col.header;
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } }; // Primary Indigo
        cell.alignment = { vertical: 'middle', horizontal: col.type === 'currency' ? 'right' : 'left' };
        cell.border = {
          bottom: { style: 'medium', color: { argb: 'FF1E293B' } },
        };
      });

      // Add Rows or Empty State Notice
      if (table.rows.length === 0) {
        sheet.mergeCells(headerRowIndex + 1, 1, headerRowIndex + 2, table.columns.length || 1);
        const emptyCell = sheet.getCell(headerRowIndex + 1, 1);
        emptyCell.value = 'No data available for the selected filters.';
        emptyCell.font = { italic: true, bold: true, color: { argb: 'FFE11D48' } };
        emptyCell.alignment = { vertical: 'middle', horizontal: 'center' };
      } else {
        table.rows.forEach((row, rIdx) => {
          const rowNum = headerRowIndex + 1 + rIdx;
          table.columns.forEach((col, cIdx) => {
            const cell = sheet.getCell(rowNum, cIdx + 1);
            let val = row[col.key];

            if (col.type === 'currency') {
              cell.value = Number(val) || 0;
              cell.numFmt = '₹#,##0.00';
              cell.alignment = { horizontal: 'right' };
            } else if (col.type === 'date') {
              cell.value = val ? String(val) : '—';
              cell.alignment = { horizontal: 'center' };
            } else if (typeof val === 'number') {
              cell.value = val;
              cell.alignment = { horizontal: 'right' };
            } else {
              cell.value = val !== undefined && val !== null ? String(val) : '—';
              cell.alignment = { horizontal: 'left' };
            }

            // Alternating Row Fill
            if (rIdx % 2 === 1) {
              cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
            }
          });
        });

        // Totals Row if present
        if (table.totals) {
          const totalRowNum = headerRowIndex + 1 + table.rows.length;
          sheet.getCell(totalRowNum, 1).value = 'TOTAL';
          sheet.getCell(totalRowNum, 1).font = { bold: true };

          table.columns.forEach((col, cIdx) => {
            const cell = sheet.getCell(totalRowNum, cIdx + 1);
            cell.font = { bold: true };
            cell.border = {
              top: { style: 'thin', color: { argb: 'FF94A3B8' } },
              bottom: { style: 'double', color: { argb: 'FF0F172A' } },
            };

            if (table.totals && table.totals[col.key] !== undefined) {
              const totVal = Number(table.totals[col.key]) || 0;
              cell.value = totVal;
              if (col.type === 'currency') cell.numFmt = '₹#,##0.00';
              cell.alignment = { horizontal: 'right' };
            }
          });
        }

        // Enable Auto-Filter
        sheet.autoFilter = {
          from: { row: headerRowIndex, column: 1 },
          to: { row: headerRowIndex, column: table.columns.length },
        };
      }

      // Auto Column Width Calculation
      table.columns.forEach((col, cIdx) => {
        let maxLen = col.header.length;
        table.rows.forEach(r => {
          const str = String(r[col.key] || '');
          if (str.length > maxLen) maxLen = str.length;
        });
        sheet.getColumn(cIdx + 1).width = Math.min(Math.max(maxLen + 4, col.width || 15), 45);
      });
    });

    // Save Workbook
    if (record.format === 'csv') {
      await workbook.csv.writeFile(`${targetPath}.csv`);
    } else {
      await workbook.xlsx.writeFile(`${targetPath}.xlsx`);
    }
  }
}
