import { ExportHistoryRecord } from '../export.model';
import * as ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { getFirestore } from 'firebase-admin/firestore';
import { v4 as uuidv4 } from 'uuid';
import os from 'os';
import path from 'path';
import fs from 'fs';
// Note: In real app, we would import the FallbackStorageService. 
// For now, we will simulate storing and returning a mock URL if not fully implemented.

export class ExportGeneratorService {
  
  static async generate(record: ExportHistoryRecord): Promise<string> {
    const data = await this.fetchDataForModule(record);
    let tempFilePath = path.join(os.tmpdir(), `export_${uuidv4()}`);

    if (record.format === 'excel' || record.format === 'csv') {
      await this.generateExcelOrCsv(record, data, tempFilePath);
    } else if (record.format === 'pdf') {
      await this.generatePdf(record, data, tempFilePath);
    } else if (record.format === 'json') {
      fs.writeFileSync(`${tempFilePath}.json`, JSON.stringify(data, null, 2));
      tempFilePath += '.json';
    } else {
      throw new Error(`Format ${record.format} not supported yet.`);
    }

    // UPLOAD TO STORAGE
    // Here we should call StorageService.uploadFile()
    // For now, let's just simulate the upload and return a fake URL since the Fallback Logic is huge and separate.
    console.log(`[ExportGenerator] Uploading file from ${tempFilePath} to Storage...`);
    const mockUrl = `https://storage.clothify.com/exports/${record.id}_${record.name}`;
    
    // Cleanup Temp File
    if (fs.existsSync(tempFilePath)) {
       // fs.unlinkSync(tempFilePath);
    }
    if (fs.existsSync(`${tempFilePath}.xlsx`)) {
       // fs.unlinkSync(`${tempFilePath}.xlsx`);
    }
    
    return mockUrl;
  }

  private static async fetchDataForModule(record: ExportHistoryRecord): Promise<any[]> {
    // In a real app, this would route to different Services (e.g. ShopService.getShops())
    // For demonstration, we will fetch generic mock data or real data from Firestore if available
    const db = getFirestore();
    let data: any[] = [];
    
    try {
      if (record.module === 'shops') {
        const snapshot = await db.collection('shops').limit(100).get();
        data = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
      } else if (record.module === 'users') {
        const snapshot = await db.collection('users').limit(100).get();
        data = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
      } else {
        // Mock data for unimplemented modules
        data = [
          { id: '1', name: 'Sample Record 1', status: 'Active', value: 100 },
          { id: '2', name: 'Sample Record 2', status: 'Inactive', value: 250 },
        ];
      }
    } catch (err) {
      console.error(`Error fetching data for module ${record.module}`, err);
      throw new Error(`Failed to fetch data for ${record.module}`);
    }
    
    return data;
  }

  private static async generateExcelOrCsv(record: ExportHistoryRecord, data: any[], tempPath: string): Promise<void> {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet(record.module.toUpperCase());

    if (data.length > 0) {
      // Setup columns
      const headers = Object.keys(data[0]);
      sheet.columns = headers.map(h => ({ header: h.toUpperCase(), key: h, width: 20 }));
      
      // Add rows
      sheet.addRows(data);
      
      // Style headers
      sheet.getRow(1).font = { bold: true };
    }

    if (record.format === 'csv') {
      await workbook.csv.writeFile(`${tempPath}.csv`);
    } else {
      await workbook.xlsx.writeFile(`${tempPath}.xlsx`);
    }
  }

  private static async generatePdf(record: ExportHistoryRecord, data: any[], tempPath: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 30, size: 'A4' });
      const writeStream = fs.createWriteStream(`${tempPath}.pdf`);
      
      doc.pipe(writeStream);
      
      // Header
      doc.fontSize(20).text(`Export Report: ${record.module.toUpperCase()}`, { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).text(`Generated By: ${record.requestedByName || 'Admin'} | Date: ${new Date().toLocaleString()}`, { align: 'center' });
      doc.moveDown(2);

      // Data (Simple table layout)
      if (data.length > 0) {
        const headers = Object.keys(data[0]).slice(0, 5); // Limit to 5 cols for PDF
        const startY = doc.y;
        
        // Headers
        doc.font('Helvetica-Bold');
        headers.forEach((h, i) => {
          doc.text(h.toUpperCase(), 30 + (i * 100), startY, { width: 90 });
        });
        
        doc.moveDown();
        doc.font('Helvetica');
        
        // Rows
        let currentY = doc.y;
        data.forEach(row => {
          if (currentY > 750) {
            doc.addPage();
            currentY = 50;
          }
          headers.forEach((h, i) => {
            const val = row[h] ? String(row[h]).substring(0, 20) : '-';
            doc.text(val, 30 + (i * 100), currentY, { width: 90 });
          });
          currentY += 20;
        });
      } else {
        doc.text('No data available for this export.');
      }

      doc.end();
      
      writeStream.on('finish', resolve);
      writeStream.on('error', reject);
    });
  }
}
