import PDFDocument from 'pdfkit';
import fs from 'fs';
import { ExportHistoryRecord } from '../export.model';
import { ReportDataResult } from './report-data-fetcher.service';

export class PdfReportBuilder {

  static async build(record: ExportHistoryRecord, dataResult: ReportDataResult, targetPath: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        margin: 36,
        size: 'A4',
        bufferPages: true,
      });

      const fullPath = `${targetPath}.pdf`;
      const writeStream = fs.createWriteStream(fullPath);
      doc.pipe(writeStream);

      const brandPrimary = '#4f46e5'; // Indigo
      const brandDark = '#0f172a';    // Slate 900
      const brandMuted = '#64748b';   // Slate 500
      const bgLight = '#f8fafc';      // Slate 50

      // ── HEADER BANNER ─────────────────────────────────────────────────────────────
      doc.rect(36, 36, 523, 60).fill(brandDark);

      // DashKit Logo & Title
      doc.fillColor('#ffffff').fontSize(16).font('Helvetica-Bold').text('DashKit Enterprise', 48, 48);
      doc.fontSize(9).font('Helvetica').text('PLATFORM MANAGEMENT REPORTING SYSTEM', 48, 68);

      doc.fillColor('#a5b4fc').fontSize(12).font('Helvetica-Bold').text(dataResult.title, 48, 80, { width: 500, align: 'left' });

      doc.y = 110;

      // ── METADATA PANEL ─────────────────────────────────────────────────────────────
      doc.rect(36, doc.y, 523, 55).fill(bgLight).stroke('#e2e8f0');
      const metaY = doc.y + 8;

      doc.fillColor(brandDark).fontSize(8).font('Helvetica-Bold');
      doc.text('Report Name:', 48, metaY);
      doc.text('Generated By:', 48, metaY + 14);
      doc.text('Date Range:', 48, metaY + 28);

      doc.font('Helvetica').fillColor('#334155');
      doc.text(record.name, 110, metaY);
      doc.text(record.requestedByName || 'Super Admin', 110, metaY + 14);
      doc.text(`${record.filters?.startDate || 'All Time'} to ${record.filters?.endDate || 'Present'}`, 110, metaY + 28);

      doc.font('Helvetica-Bold').fillColor(brandDark);
      doc.text('Generated Date:', 300, metaY);
      doc.text('Total Records:', 300, metaY + 14);
      doc.text('Applied Filters:', 300, metaY + 28);

      doc.font('Helvetica').fillColor('#334155');
      doc.text(new Date().toLocaleString('en-IN'), 380, metaY);
      doc.text(String(dataResult.totalRecords), 380, metaY + 14);
      doc.text(record.filters?.status ? `Status: ${record.filters.status}` : 'Default', 380, metaY + 28);

      doc.y = metaY + 50;

      // ── EXECUTIVE SUMMARY KPI CARDS GRID ──────────────────────────────────────────
      if (dataResult.kpis && dataResult.kpis.length > 0) {
        doc.fillColor(brandPrimary).fontSize(11).font('Helvetica-Bold').text('EXECUTIVE SUMMARY & KPI HIGHLIGHTS', 36, doc.y);
        doc.moveDown(0.5);

        const cardWidth = 120;
        const cardHeight = 45;
        const startX = 36;
        let cardY = doc.y;

        dataResult.kpis.slice(0, 4).forEach((kpi, idx) => {
          const x = startX + (idx * (cardWidth + 14));
          doc.rect(x, cardY, cardWidth, cardHeight).fill(bgLight).stroke('#cbd5e1');

          // Left Accent Stripe
          doc.rect(x, cardY, 4, cardHeight).fill(brandPrimary);

          doc.fillColor(brandMuted).fontSize(7).font('Helvetica-Bold').text(kpi.label.toUpperCase(), x + 8, cardY + 6, { width: cardWidth - 12 });
          doc.fillColor(brandDark).fontSize(11).font('Helvetica-Bold').text(String(kpi.value), x + 8, cardY + 18, { width: cardWidth - 12 });

          if (kpi.subtext) {
            doc.fillColor('#059669').fontSize(6.5).font('Helvetica').text(kpi.subtext, x + 8, cardY + 32, { width: cardWidth - 12 });
          }
        });

        doc.y = cardY + cardHeight + 15;
      }

      // ── DATA TABLES ───────────────────────────────────────────────────────────────
      dataResult.tables.forEach((table) => {
        if (doc.y > 680) doc.addPage();

        doc.fillColor(brandDark).fontSize(11).font('Helvetica-Bold').text(table.title.toUpperCase(), 36, doc.y);
        doc.moveDown(0.4);

        const startX = 36;
        const tableWidth = 523;
        const cols = table.columns;
        const colWidth = tableWidth / cols.length;

        // Header Helper Function
        const renderTableHeader = (yPos: number) => {
          doc.rect(startX, yPos, tableWidth, 18).fill(brandDark);
          doc.fillColor('#ffffff').fontSize(7.5).font('Helvetica-Bold');
          cols.forEach((col, i) => {
            const align = col.type === 'currency' ? 'right' : 'left';
            doc.text(col.header, startX + (i * colWidth) + 4, yPos + 5, { width: colWidth - 8, align });
          });
        };

        let currentY = doc.y;
        renderTableHeader(currentY);
        currentY += 18;

        if (table.rows.length === 0) {
          // Zero-Data State Notice
          doc.rect(startX, currentY, tableWidth, 25).fill('#fff1f2').stroke('#fecdd3');
          doc.fillColor('#be123c').fontSize(9).font('Helvetica-Bold')
            .text('No data available for the selected filters.', startX, currentY + 7, { width: tableWidth, align: 'center' });
          currentY += 30;
        } else {
          // Render Rows
          table.rows.forEach((row, rIdx) => {
            if (currentY > 740) {
              doc.addPage();
              currentY = 40;
              renderTableHeader(currentY);
              currentY += 18;
            }

            if (rIdx % 2 === 1) {
              doc.rect(startX, currentY, tableWidth, 16).fill(bgLight);
            }

            doc.fillColor('#334155').fontSize(7).font('Helvetica');
            cols.forEach((col, cIdx) => {
              let val = row[col.key];
              if (col.type === 'currency') {
                val = `₹${(Number(val) || 0).toLocaleString('en-IN')}`;
              } else if (val === undefined || val === null) {
                val = '—';
              } else {
                val = String(val).substring(0, 25);
              }

              const align = col.type === 'currency' ? 'right' : 'left';
              doc.text(val, startX + (cIdx * colWidth) + 4, currentY + 4, { width: colWidth - 8, align });
            });

            currentY += 16;
          });

          // Totals Row
          if (table.totals) {
            if (currentY > 740) {
              doc.addPage();
              currentY = 40;
            }

            doc.rect(startX, currentY, tableWidth, 18).fill('#f1f5f9').stroke('#cbd5e1');
            doc.fillColor(brandDark).fontSize(7.5).font('Helvetica-Bold');
            doc.text('TOTAL', startX + 4, currentY + 5);

            cols.forEach((col, cIdx) => {
              if (table.totals && table.totals[col.key] !== undefined) {
                const totVal = Number(table.totals[col.key]) || 0;
                const fmtVal = col.type === 'currency' ? `₹${totVal.toLocaleString('en-IN')}` : String(totVal);
                doc.text(fmtVal, startX + (cIdx * colWidth) + 4, currentY + 5, { width: colWidth - 8, align: 'right' });
              }
            });

            currentY += 22;
          }
        }

        doc.y = currentY + 10;
      });

      // ── FOOTERS (PAGE NUMBERS) ──────────────────────────────────────────────────
      const pages = doc.bufferedPageRange();
      for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        doc.rect(36, 765, 523, 0.5).fill('#cbd5e1');
        doc.fillColor(brandMuted).fontSize(7).font('Helvetica')
          .text(`DashKit Enterprise Platform Report — Confidential`, 36, 772);
        doc.text(`Page ${i + 1} of ${pages.count}`, 36, 772, { width: 523, align: 'right' });
      }

      doc.end();

      writeStream.on('finish', resolve);
      writeStream.on('error', reject);
    });
  }
}
